DROP DATABASE IF EXISTS CRECHE;
CREATE DATABASE CRECHE;
USE CRECHE;

# =======================
# 📘 TABELAS BASE
# =======================

CREATE TABLE PESSOA (
    ID_PESSOA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    CPF CHAR(11) UNIQUE NOT NULL,
    RG VARCHAR(20) UNIQUE NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    OUTRO_CONTATO VARCHAR(20)
);

CREATE TABLE ENDERECO (
    ID_ENDERECO BIGINT AUTO_INCREMENT PRIMARY KEY,
    LOGRADOURO VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(20) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    BAIRRO VARCHAR(100) NOT NULL,
    MUNICIPIO VARCHAR(100) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    UF CHAR(2) NOT NULL,
    PONTO_REFERENCIA VARCHAR(100),
    TELEFONE_RESIDENCIAL VARCHAR(20),
    UNIQUE(LOGRADOURO, NUMERO, BAIRRO, MUNICIPIO, UF, CEP)
);

CREATE TABLE TIPO_AUXILIO (
    ID_TIPO_AUXILIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_AUXILIO VARCHAR(255) UNIQUE
);

CREATE TABLE CLASSIFICACAO_ESPECIAL (
    ID_CLASSIFICACAO_ESPECIAL INT AUTO_INCREMENT PRIMARY KEY,
    CLASSIFICACAO_ESPECIAL VARCHAR(255),
    CODIGO VARCHAR(255),
    DESCRICAO TEXT,
    STATUS_CLASSIFICACAO_ESPECIAL BOOLEAN NOT NULL
);

CREATE TABLE ALERGIA (
    ID_ALERGIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_ALERGIA VARCHAR(100)
);

CREATE TABLE TIPO_RESPONSAVEL (
    ID_TIPO_RESPONSAVEL INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_RESPONSAVEL VARCHAR(255)
);

CREATE TABLE RESPONSAVEL (
    ID_RESPONSAVEL INT AUTO_INCREMENT PRIMARY KEY,
    ID_TIPO_RESPONSAVEL INT,
    ID_PESSOA INT NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    LOCAL_TRABALHO VARCHAR(100),
    AUXILIO_GOV BOOLEAN NOT NULL,
    ID_TIPO_AUXILIO INT,
    NUMERO_NIS VARCHAR(255),
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA),
    FOREIGN KEY (ID_TIPO_AUXILIO) REFERENCES TIPO_AUXILIO(ID_TIPO_AUXILIO),
    FOREIGN KEY (ID_TIPO_RESPONSAVEL) REFERENCES TIPO_RESPONSAVEL(ID_TIPO_RESPONSAVEL)
);

CREATE TABLE CRIANCA (
    ID_CRIANCA INT AUTO_INCREMENT PRIMARY KEY,
    FOTO VARCHAR(255),
    NOME VARCHAR(255),
	CPF CHAR(11) UNIQUE NOT NULL,
    RG VARCHAR(20) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    SEXO ENUM('MASCULINO','FEMININO','OUTRO') NOT NULL,
    COR_RACA ENUM('BRANCA','PRETA','PARDA','AMARELA','INDIGENA', 'OUTRO'),
    POSSUI_IRMAO_CRECHE BOOLEAN DEFAULT False,
    POSSUI_IRMAO_GEMEO BOOLEAN DEFAULT False,
    CARTSUS CHAR(15) UNIQUE NOT NULL,
    UNIDADE_SAUDE VARCHAR(100),
    MUNICIPIO_NASCIMENTO VARCHAR(255),
    MUNICIPIORESGISTRO VARCHAR(255),
    CARTORIO_REGISTRO VARCHAR(255),
    CERTIDAO_NASCIMENTO_NUM VARCHAR(255),
    DATA_EMISSAO_CERTIDAO DATE,
    ORG_EMISSOR_CERTIDAO VARCHAR(10),
    RESTRICAO_ALIMENTAR BOOLEAN NOT NULL,
    DESCRICAO_RESTRICOES_ALIMENTARES VARCHAR(255),
    ALERGIA BOOLEAN NOT NULL,
    PROBLEMA_SAUDE TEXT,
    RESTRI_ALIMENTAR TEXT,
    MOB_RED ENUM('TEMPORARIA','PERMANENTE','NENHUMA'),
    DEF_MULTI BOOLEAN NOT NULL,
    EDUC_ESPECIAL BOOLEAN NOT NULL,
    RESPONSAVEL_BENEFICIARIO_AUXILIO_GOV BOOLEAN NOT NULL,
    ID_RESPONSAVEL INT,
    ID_TIPO_AUXILIO INT,
    ID_CLASSIFICACAO_ESPECIAL INT,
    STATUS_CLASSIFICACAO_ESPECIAL BOOLEAN NOT NULL DEFAULT FALSE,
    ID_PAI INT,
    ID_MAE INT,
    ID_IRMAO_GEMEO INT,
    FOREIGN KEY (ID_TIPO_AUXILIO) REFERENCES TIPO_AUXILIO(ID_TIPO_AUXILIO),
    FOREIGN KEY (ID_RESPONSAVEL) REFERENCES RESPONSAVEL(ID_RESPONSAVEL),
    FOREIGN KEY (ID_CLASSIFICACAO_ESPECIAL) REFERENCES CLASSIFICACAO_ESPECIAL(ID_CLASSIFICACAO_ESPECIAL),
    FOREIGN KEY (ID_PAI) REFERENCES PESSOA(ID_PESSOA),
    FOREIGN KEY (ID_MAE) REFERENCES PESSOA(ID_PESSOA),
    FOREIGN KEY (ID_IRMAO_GEMEO) REFERENCES CRIANCA(ID_CRIANCA)
);

CREATE TABLE CRIANCA_ALERGIA (
    ID_CRIANCA_ALERGIA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CRIANCA INT NOT NULL,
    ID_ALERGIA INT NOT NULL,
    FOREIGN KEY (ID_ALERGIA) REFERENCES ALERGIA(ID_ALERGIA),
    FOREIGN KEY (ID_CRIANCA) REFERENCES CRIANCA(ID_CRIANCA)
);

CREATE TABLE MEMBRO_FAMILIA (
    ID_MEMBRO_FAMILIA BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_CRIANCA INT NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    IDADE INT NOT NULL,
    PARENTESCO ENUM('MAE','PAI','IRMAO','IRMA','AVO','TIO','TIA','RESPONSAVEL_LEGAL','OUTRO'),
    SITUACAO_ESCOLAR ENUM(
        'CRECHE','PRE_ESCOLA','ENSINO_FUNDAMENTAL_1_1_5_ANO',
        'ENSINO_FUNDAMENTAL_2_6_9_ANO','ENSINO_FUNDAMENTAL_INCOMPLETO',
        'ENSINO_FUNDAMENTAL_COMPLETO','ENSINO_MEDIO_INCOMPLETO',
        'ENSINO_MEDIO_COMPLETO','ENSINO_TECNICO_INTEGRADO_MEDIO',
        'ENSINO_MEDIO_PROFISSIONALIZANTE','ENSINO_SUPERIOR_INCOMPLETO',
        'ENSINO_SUPERIOR_COMPLETO','POS_GRADUACAO_LATO_SENSU_ESPECIALIZACAO',
        'MESTRADO','DOUTORADO','POS_DOUTORADO','EJA_FUNDAMENTAL',
        'EJA_MEDIO','ALFABETIZACAO_DE_ADULTOS','ANALFABETO','NAO_INFORMADO'
    ),
    SITUACAO_EMPREGO ENUM(
        'EMPREGADO_FORMAL','EMPREGADO_INFORMAL','SERVIDOR_PUBLICO','AUTONOMO',
        'EMPREGADOR','APOSENTADO','PENSIONISTA','DESEMPREGADO','DO_LAR',
        'ESTUDANTE','BOLSISTA','INCAPAZ_TRABALHAR','OUTRO'
    ),
    RENDA DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_CRIANCA) REFERENCES CRIANCA(ID_CRIANCA)
);

CREATE TABLE PESSOA_AUTORIZADA (
    ID_PESSOA_AUT INT AUTO_INCREMENT PRIMARY KEY,
    ID_PESSOA INT,
    ID_CRIANCA INT,
    PARENTESCO ENUM(
        'MAE','PAI','IRMAO','IRMA','AVO','TIO','TIA',
        'RESPONSAVEL_LEGAL','PRIMO','PRIMA','NENHUM'
    ),
    TELEFONE VARCHAR(50),
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA),
    FOREIGN KEY (ID_CRIANCA) REFERENCES CRIANCA(ID_CRIANCA)
);

# =======================
# 🏠 NOVA TABELA DE BENS DA FAMÍLIA COM ENUM
# =======================

CREATE TABLE TIPO_BEM (
    ID_TIPO_BEM INT AUTO_INCREMENT PRIMARY KEY,
    NOME_BEM ENUM(
        'TV',
        'DVD',
        'RADIO',
        'COMPUTADOR',
        'NOTEBOOK',
        'TELEFONE_FIXO',
        'TELEFONE_CELULAR',
        'TABLET',
        'INTERNET',
        'TV_ASSINATURA',
        'FOGAO',
        'GELADEIRA',
        'FREEZER',
        'MICROONDAS',
        'MAQUINA_LAVAR_ROUPA',
        'AR_CONDICIONADO',
        'BICICLETA',
        'MOTO',
        'AUTOMOVEL'
    ) UNIQUE NOT NULL,
    CATEGORIA ENUM('ELETRODOMESTICO', 'ELETRONICO', 'VEICULO', 'COMUNICACAO') NOT NULL
);

CREATE TABLE SITUACAO_HABITACIONAL (
    ID_SITUACAO_HAB INT AUTO_INCREMENT PRIMARY KEY,
    CASA_PROPRIA BOOLEAN,
    CASA_CEDIDA BOOLEAN,
    CASA_ALUGADA BOOLEAN,
    VALOR_ALUGUEL DECIMAL(10,2),
    NUMERO_COMODOS INT,
    TIPO_PISO ENUM('CIMENTO','LAJOTA','CHAO_BATIDO','CERAMICA','MADEIRA','OUTRO'),
    TIPO_MORADIA ENUM('TIJOLO','TAIPA','MADEIRA','MISTA','ALVENARIA','OUTRO'),
    TIPO_COBERTURA ENUM('TELHA','ZINCO','PALHA','LAJE','OUTRO'),
    FOSSA BOOLEAN,
    CIFON BOOLEAN,
    ENERGIA_ELETRICA BOOLEAN,
    AGUA_ENCANADA BOOLEAN,
    COLETOR_PUBLICO BOOLEAN
);

CREATE TABLE COMPOSICAO_FAMILIAR (
    ID_COMPOSICAO_FAMILIAR INT AUTO_INCREMENT PRIMARY KEY,
    ID_CRIANCA INT NOT NULL,
    RENDA_FAMILIAR_TOTAL DECIMAL(10,2) NOT NULL,
    RENDA_PER_CAPITA DECIMAL(10,2) NOT NULL,
    TOTAL_MEMBROS INT,
    FOREIGN KEY (ID_CRIANCA) REFERENCES CRIANCA(ID_CRIANCA)
);

# =======================
# 📄 MATRÍCULAS
# =======================

CREATE TABLE PRE_MATRICULA (
    ID_PRE_MATRICULA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CRIANCA INT NOT NULL,
    SERIE_TEMP VARCHAR(50),
	ANO_LETIVO_TEMP INT,
    DATA_PREMATRICULA DATE NOT NULL,
    SITUACAO_HABITACIONAL INT,
    SITUACAO_PREMATRICULA ENUM('APROVADA','EM_ANALISE','CANCELADA','REPROVADA') DEFAULT 'EM_ANALISE',
    OBSERVACAO TEXT,
    FOREIGN KEY (ID_CRIANCA) REFERENCES CRIANCA(ID_CRIANCA),
    FOREIGN KEY (SITUACAO_HABITACIONAL) REFERENCES SITUACAO_HABITACIONAL(ID_SITUACAO_HAB)
);

CREATE TABLE MATRICULA (
    ID_MATRICULA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CRIANCA INT NOT NULL,
    ID_PRE_MATRICULA INT,
    DATA_MATRICULA DATE,
    SERIE ENUM('BERCARIO_I', 'BERCARIO_II', 'MATERNAL_I', 'MATERNAL_II', 'PRE_I', 'PRE_II'),
    ANO_LETIVO YEAR NOT NULL,
    ORIENT_RECEBIDA BOOLEAN,
    DATA_DESLIGAMENTO DATE,
    SITUACAO_MAT ENUM('ATIVA','CONCLUIDA','CANCELADA', 'VENCIDA') DEFAULT 'ATIVA',
    DATA_VENCIMENTO DATE NOT NULL,
    FOREIGN KEY (ID_CRIANCA) REFERENCES CRIANCA(ID_CRIANCA),
    FOREIGN KEY (ID_PRE_MATRICULA) REFERENCES PRE_MATRICULA(ID_PRE_MATRICULA)
);

CREATE TABLE BENS_FAMILIA (
    ID_BENS_FAMILIA BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_COMPOSICAO_FAMILIAR INT NOT NULL,
    ID_TIPO_BEM INT NOT NULL,
    POSSUI BOOLEAN NOT NULL DEFAULT TRUE,
    QUANTIDADE INT DEFAULT 1,
    FOREIGN KEY (ID_COMPOSICAO_FAMILIAR) REFERENCES COMPOSICAO_FAMILIAR(ID_COMPOSICAO_FAMILIAR),
    FOREIGN KEY (ID_TIPO_BEM) REFERENCES TIPO_BEM(ID_TIPO_BEM)
);


# =======================
# 🧾 HISTÓRICO DE MATRÍCULA (somente sistema)
# =======================

CREATE TABLE HISTORICO_MATRICULA (
    ID_HIST_MATRI INT AUTO_INCREMENT PRIMARY KEY,
    ID_MATRICULA INT NOT NULL,
    ID_CRIANCA INT NOT NULL,
    DATA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ACAO ENUM('CRIACAO','RENOVACAO','CANCELAMENTO','CONCLUSAO','ALTERACAO') NOT NULL,
    FOREIGN KEY (ID_CRIANCA) REFERENCES CRIANCA(ID_CRIANCA),
    FOREIGN KEY (ID_MATRICULA) REFERENCES MATRICULA(ID_MATRICULA)
);


-- =======================
-- 💰 POPULANDO TIPO_AUXILIO
-- =======================
INSERT INTO TIPO_AUXILIO (NOME_AUXILIO) VALUES
('Nenhum'),
('Bolsa Família'),
('Auxílio Brasil'),
('BPC - LOAS'),
('Bolsa Cidadã'),
('Auxílio Emergencial'),
('Vale Gás'),
('Cesta Básica'),
('Bolsa Escola'),
('Auxílio Moradia'),
('Bolsa Trabalho');


-- =======================
-- 🎓 POPULANDO CLASSIFICACAO_ESPECIAL
-- =======================
INSERT INTO CLASSIFICACAO_ESPECIAL (CLASSIFICACAO_ESPECIAL, CODIGO, DESCRICAO, STATUS_CLASSIFICACAO_ESPECIAL) VALUES
('Nenhum', '00000', 'Nenhuma Deficiência', True),
('Altas Habilidades', 'AH001', 'Superdotação intelectual comprovada', TRUE),
('Deficiência Física', 'DF002', 'Mobilidade reduzida permanente', TRUE),
('Deficiência Visual', 'DV003', 'Baixa visão ou cegueira', TRUE),
('Deficiência Auditiva', 'DA004', 'Perda auditiva parcial ou total', TRUE),
('TEA - Nível 1', 'TEA005', 'Transtorno do Espectro Autista - Suporte', TRUE),
('TDAH', 'TDAH006', 'Transtorno de Déficit de Atenção', TRUE),
('Deficiência Intelectual', 'DI007', 'Comprometimento cognitivo', TRUE),
('Síndrome de Down', 'SD008', 'Trissomia do 21', TRUE),
('Paralisia Cerebral', 'PC009', 'Lesão cerebral congênita', TRUE),
('Deficiência Múltipla', 'DM010', 'Duas ou mais deficiências associadas', TRUE);

-- =======================
-- 🤧 POPULANDO ALERGIA
-- =======================
INSERT INTO ALERGIA (NOME_ALERGIA) VALUES
('Nenhum'),
('Leite'),
('Ovo'),
('Amendoim'),
('Frutos do mar'),
('Glúten'),
('Soja'),
('Corante artificial'),
('Pólen'),
('Ácaros'),
('Penicilina');

-- =======================
-- 👨‍👩‍👧 POPULANDO TIPO_RESPONSAVEL
-- =======================
INSERT INTO TIPO_RESPONSAVEL (TIPO_RESPONSAVEL) VALUES
('Pai'),
('Mãe'),
('Avô'),
('Avó'),
('Tio'),
('Tia'),
('Irmão'),
('Irmã'),
('Responsável Legal'),
('Tutor Judicial');

-- =======================
-- 👨‍👩‍👧 POPULANDO TIPO_BEMs
-- =======================
INSERT INTO TIPO_BEM (NOME_BEM, CATEGORIA) VALUES
-- ELETRODOMÉSTICOS
('TV', 'ELETRODOMESTICO'),
('DVD', 'ELETRODOMESTICO'),
('RADIO', 'ELETRODOMESTICO'),
('FOGAO', 'ELETRODOMESTICO'),
('GELADEIRA', 'ELETRODOMESTICO'),
('FREEZER', 'ELETRODOMESTICO'),
('MICROONDAS', 'ELETRODOMESTICO'),
('MAQUINA_LAVAR_ROUPA', 'ELETRODOMESTICO'),
('AR_CONDICIONADO', 'ELETRODOMESTICO'),

-- ELETRÔNICOS
('COMPUTADOR', 'ELETRONICO'),
('NOTEBOOK', 'ELETRONICO'),
('TABLET', 'ELETRONICO'),

-- COMUNICAÇÃO
('TELEFONE_FIXO', 'COMUNICACAO'),
('TELEFONE_CELULAR', 'COMUNICACAO'),
('INTERNET', 'COMUNICACAO'),
('TV_ASSINATURA', 'COMUNICACAO'),

-- VEÍCULOS
('BICICLETA', 'VEICULO'),
('MOTO', 'VEICULO'),
('AUTOMOVEL', 'VEICULO');
